remove errs pack and change logic for processing errors
retailcrm/api-client-go pull request #48
Opened 2021-04-15 06:25 UTC by RenCurs

2021-04-19 09:28 UTC, Neur0toxine requested changes

2021-04-20 18:19 UTC, RenCurs commented on v5/client.go
>  	}
Да, но там в каждом методе ответ демаршализируется в определенную структуру, то есть если выносить GET/POST запросы, то нужно тогда и структуру передавать еще одним параметром в эти запросы, в которую будут данные записываться, так?

2021-04-20 18:30 UTC, RenCurs commented on v5/error_test.go
> +		if eq := expEr.Errors["0"] == expected["0"]; eq != true {
В смысле так использовать `reflect.DeepEqual(expEr.Errors["0"], expected["0"])` или `reflect.DeepEqual(expEr, expected)` ? В последнем случае они же не равны будут из-за разных типов.

2021-04-20 18:34 UTC, Neur0toxine commented on v5/error_test.go
> +		if eq := expEr.Errors["0"] == expected["0"]; eq != true {
Используй для ожидаемого значения тип `APIErrorsList`. Тогда разные типы проблемой не будут, и проверяться будут сами данные.
Проверять нужно как во втором случае.

2021-04-20 18:39 UTC, Neur0toxine commented on v5/client.go
>  	}
При ответе с ошибкой от API придёт код 4xx. При сбое (в т.ч. когда не гарантируется ни формат ответа, ни его данные) придёт код 5xx. Достаточно определять по коду ответа ошибку, и если ответ ошибочный - десериализовать его в `APIError`. Сама `APIError` имплементирует `error` - поэтому из методов, реализующих сами запросы можно вернуть `APIError` в качестве `error`, а логика клиентского кода уже везде учитывает возможность возврата ошибки.

2021-04-21 14:28 UTC, Neur0toxine requested changes

2021-04-21 14:28 UTC, Neur0toxine commented on v5/marshaling.go
> +	m := make(map[string]string)
Здесь желательно использовать преаллокацию мапы под размер данных.

2021-04-23 10:10 UTC, Neur0toxine approved these changes

2021-04-26 09:09 UTC, merged