updated Site definition
retailcrm/api-client-go pull request #66
Opened 2022-04-27 06:16 UTC by pm14kas

2022-04-27 09:42 UTC, Neur0toxine approved these changes

2022-04-27 09:44 UTC, Neur0toxine requested changes
Сразу не увидел: на `DefaultForCrm` скорее всего будет ругаться линтер т.к. это поле скорее будет называться `DefaultForCRM`. Предыдущий аппрув недействителен.

2022-04-28 06:27 UTC, pm14kas commented
Поправил

2022-04-28 08:10 UTC, Neur0toxine approved these changes

2022-04-28 08:18 UTC, merged